name: aradia-backend
version: '0.1.0.0'
category: Discord
author: David Kraeutmann
maintainer: kane@kane.cx
copyright: 2017 David Kraeutmann
license: BSD3
github: KaneTW/aradia-backend
extra-source-files:
- README.md

default-extensions:
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - FunctionalDependencies
  - TypeFamilies
  - TemplateHaskell
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - TypeOperators
  - ConstraintKinds
  - ScopedTypeVariables
  - GADTs
  - DeriveTraversable
  - QuasiQuotes
  - TypeApplications
  - RankNTypes
  - LambdaCase
  - TypeInType
  - StandaloneDeriving
library:
  source-dirs: src
  dependencies:
  - base >=4.10 && <5
  - template-haskell
  - split
  - text >=1.2
  - lens >=4.15
  - mtl >=2.2
  - lifted-base >=0.2
  - monad-control >=1.0
  - transformers >=0.5
  - transformers-base >=0.4
  - megaparsec >=6.2
  - bytestring >=0.10
  - aeson >=1.2
  - servant >=0.11
  - vector >=0.12
  - scientific >=0.3
  - time >=1.8
  - integer-logarithms >=1.0
  - containers
  - unordered-containers
  - singletons
  - pretty-show
